name: DeployDev4

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: ls
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.KEY }}" > "$HOME/.ssh/id_rsa"
      - run: chmod 600 "$HOME/.ssh/id_rsa"
      - run: echo Hello
      - run: cd "$HOME"
      - run: ls
      - run: mkdir ".ssh"
      - run: ls
      - run: cd ".ssh"
      - run: ls
      - run: cat index.html
      #- run: cat "id_rsa"
      # Deploy
      #- run: rsync -e "ssh -p 22 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . root@95.46.32.211:/home/admin/web/dev4.ukeysecurity.com/public_html
